week2_flickr
maclaren999/pi_android_school_autumn_2020 pull request #1
Opened 2020-11-19 20:01 UTC by maclaren999

AsyncTask, second activity for WebView. PNG Splash creen icon.

2020-11-20 14:42 UTC, debuggerUA requested changes
Работает правильно, исправь замечания.

2020-11-20 14:42 UTC, debuggerUA commented on app/build.gradle
> +    implementation 'me.saket:better-link-movement-method:2.2.0'
И всё-таки, как сделать без этой билиотеки?

2020-11-20 14:42 UTC, debuggerUA commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/MainActivity.kt
> +        if (!requestStr.isBlank())
```suggestion
        if (requestStr.isNotBlank())
```

2020-11-20 14:42 UTC, debuggerUA commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
Не лучший способ.
На быстрых девайсах эта активити не будет видна.
Подумай и напиши в комментах как сделать по-другому.

2020-11-20 14:42 UTC, debuggerUA commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/WebViewActivity.kt
> +        title = "WebView"
UI строк не должно быть в коде

2020-11-20 14:42 UTC, debuggerUA commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/data/network/AsyncFlickrSearchTask.kt
> +    private var meTextView: WeakReference<TextView> = WeakReference(textView)
Какую роль выполняет *WeakReference* в данном случае?

2020-11-20 14:42 UTC, debuggerUA commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/data/network/AsyncFlickrSearchTask.kt
> +class AsyncFlickrSearchTask(textView: TextView, val activity: MainActivity) :
Не передавай в AsyncTask ссылки на активити, это ведёт к утечкам памяти если асинк таск "зависнет". Попробуй переделать без этой сслылки.

2020-11-20 14:42 UTC, debuggerUA commented on app/src/main/res/layout/activity_main.xml
> +        <WebView
Для чего она здесь?

2020-11-20 14:42 UTC, debuggerUA commented on app/src/main/res/layout/activity_main.xml
> +        android:text="cat"
```suggestion
        android:hint="@string/cat"
```

2020-11-20 15:03 UTC, maclaren999 commented on app/build.gradle
> +    implementation 'me.saket:better-link-movement-method:2.2.0'
Можно создать наследника Linkify и переопределить в нем onClick метод.

2020-11-20 15:04 UTC, maclaren999 commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/MainActivity.kt
> +        if (!requestStr.isBlank())
ок

2020-11-20 15:17 UTC, maclaren999 commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
Можно установить таймер на переход с помощью Handler().postDelayed()
Если длинный таймер нужен только в первый запуск, то  firstStart: Boolean можно хранить в Shared Pref.
У меня на девайсе с 845 snapdragon заставку видно секунды полторы. Вполне достаточно, как по мне.
Но могу сделать и таймер.

2020-11-20 15:18 UTC, maclaren999 commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/WebViewActivity.kt
> +        title = "WebView"
ок

2020-11-20 15:21 UTC, maclaren999 commented on app/src/main/res/layout/activity_main.xml
> +        android:text="cat"
Да, использовал для тестирования. Забыл убрать.

2020-11-20 15:24 UTC, maclaren999 commented on app/src/main/res/layout/activity_main.xml
> +        <WebView
Пробовал альтернативный вариант с WebView в главном Activity. Отказался из-за промежуточного белого кадра при смене содержимого WebView.

2020-11-20 18:08 UTC, maclaren999 commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/data/network/AsyncFlickrSearchTask.kt
> +    private var meTextView: WeakReference<TextView> = WeakReference(textView)
Если использовать обычную ссылку, то может случится утечка памяти.
Если после создания AsyncTask Activity будет уничтожена, то сборщик мусора не сможет удалить Activity из памяти, ибо на неё ссылается поле AsyncTask.

2020-11-20 18:09 UTC, maclaren999 commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/data/network/AsyncFlickrSearchTask.kt
> +class AsyncFlickrSearchTask(textView: TextView, val activity: MainActivity) :
Изначально пробовал так сделать, но не получалось. Исправил.

2020-11-23 08:22 UTC, debuggerUA commented on app/build.gradle
> +    implementation 'me.saket:better-link-movement-method:2.2.0'
Можно

2020-11-23 08:36 UTC, debuggerUA commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
не нужно

2020-11-23 08:37 UTC, debuggerUA commented on app/src/main/java/ua/maclaren99/pi_android_school_autumn_2020/data/network/AsyncFlickrSearchTask.kt
> +    private var meTextView: WeakReference<TextView> = WeakReference(textView)
Хорошо

2020-11-23 08:37 UTC, debuggerUA approved these changes

2020-11-25 09:37 UTC, merged